# Numpy Exercises 2

In [71]:
import numpy as np

import matplotlib.pyplot as plt
import random # Thư viện built-in của Python 

**Question 1**

Search for the duplicate entries (2nd occurrence onwards) in the given numpy array and mark them as `True`. First time occurrences should be `False` \
Input: `[0 0 3 0 2 4 2 2 2 2]` \
Correct Output: `[False  True False  True False False  True  True  True  True]`

In [72]:
#Init array
np.random.seed(100)
a = np.random.randint(0, 5, 10)
print('Array: ', a)
#TODO
mask = np.full_like(a, fill_value=False, dtype=bool)

_, unique_indices, counts = np.unique(a, return_index=True, return_counts=True) #sort then find unique

mask[unique_indices[counts > 1]] = True

print('Result: ', mask)

Array:  [0 0 3 0 2 4 2 2 2 2]
Result:  [ True False False False  True False False False False False]


**Question 2**

Return all items in array `a` that not in array `b` \
Input: \
`a` = `[1,2,3,4,5]` \
`b` = `[5,6,7,8,9]` \
Output: \
`[1,2,3,4]`

In [73]:
a = np.random.choice(range(10), 7, replace=False)
b = np.random.choice(range(10), 7, replace=False)
print(a,b)
#TODO
not_in_b = np.setdiff1d(a, b)
print('Items in a not in b:', not_in_b)

[5 9 7 2 6 3 4] [0 7 1 8 5 4 3]
Items in a not in b: [2 6 9]


**Question 3**

Given a vector `a`, build a new vector with 2 consecutive zeros interleaved between each value. \
Input: \
`a` = `[4, 3, 4, 9, 8]` \
Output: \
`[4. 0. 0. 3. 0. 0. 4. 0. 0. 9. 0. 0. 8.]`

In [74]:
a = np.random.randint(1, 10, 5)
#TODO

res = np.zeros(3*len(a)-2)

res[::3]=a

print(res)

[6.0 0.0 0.0 4.0 0.0 0.0 5.0 0.0 0.0 5.0 0.0 0.0 4.0]


In [75]:
a = np.random.randint(1, 10, 5)
print(a)
print(a[::3])

[8 2 2 8 8]
[8 8]


---
*For the next few questions we will work with `Iris Dataset`*

In [76]:
iris_1d = np.genfromtxt('Data/Iris.csv', delimiter=',', skip_header=1, dtype=None,encoding=None)
iris_2d = np.array([row.tolist()[:4] for row in iris_1d])
iris_2d

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3.0, 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5.0, 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5.0, 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3.0, 1.4, 0.1],
       [4.3, 3.0, 1.1, 0.1],
       [5.8, 4.0, 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1.0, 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5.0, 3.0, 1.6, 0.2],
       [5.0, 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

**Question 4**\
Filter the rows of iris_2d that has `petallength` (3rd column) > 1.5 and `sepallength` (1st column) < 5.0

In [77]:
#TODO
# Filter the rows based on conditions
filtered_rows = iris_2d[(iris_2d[:, 2] > 1.5) & (iris_2d[:, 0] < 5.0)]

filtered_rows

array([[4.8, 3.4, 1.6, 0.2],
       [4.8, 3.4, 1.9, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [4.9, 2.4, 3.3, 1.0],
       [4.9, 2.5, 4.5, 1.7]])

**Question 5**\
Add a new text column to `iris_2d`, which based on the petal length (3rd) column, such that if petal length is: \
- `Less than 3` --> 'small'
- `3-5` --> 'medium'
- `>=5` --> 'large'

In [78]:
#TODO
iris_2d[:, 2] = iris_2d[:, 2].astype(float)

# Create a new column filled with 'small'
new_col = np.full(iris_2d.shape[0], fill_value='small', dtype='U32')  # Use dtype='U32' to specify Unicode string of length 32

new_col[(iris_2d[:, 2] >= 3.0) & (iris_2d[:, 2] < 5.0)] = 'medium'
new_col[iris_2d[:, 2] >= 5.0] = 'large'

# Add the new column to iris_2d
iris_2d = np.column_stack((iris_2d, new_col))

iris_2d

array([['5.1', '3.5', '1.4', '0.2', 'small'],
       ['4.9', '3.0', '1.4', '0.2', 'small'],
       ['4.7', '3.2', '1.3', '0.2', 'small'],
       ['4.6', '3.1', '1.5', '0.2', 'small'],
       ['5.0', '3.6', '1.4', '0.2', 'small'],
       ['5.4', '3.9', '1.7', '0.4', 'small'],
       ['4.6', '3.4', '1.4', '0.3', 'small'],
       ['5.0', '3.4', '1.5', '0.2', 'small'],
       ['4.4', '2.9', '1.4', '0.2', 'small'],
       ['4.9', '3.1', '1.5', '0.1', 'small'],
       ['5.4', '3.7', '1.5', '0.2', 'small'],
       ['4.8', '3.4', '1.6', '0.2', 'small'],
       ['4.8', '3.0', '1.4', '0.1', 'small'],
       ['4.3', '3.0', '1.1', '0.1', 'small'],
       ['5.8', '4.0', '1.2', '0.2', 'small'],
       ['5.7', '4.4', '1.5', '0.4', 'small'],
       ['5.4', '3.9', '1.3', '0.4', 'small'],
       ['5.1', '3.5', '1.4', '0.3', 'small'],
       ['5.7', '3.8', '1.7', '0.3', 'small'],
       ['5.1', '3.8', '1.5', '0.3', 'small'],
       ['5.4', '3.4', '1.7', '0.2', 'small'],
       ['5.1', '3.7', '1.5', '0.4'

**Question 6**\
Find the value of second longest `petallength` of species `setosa`

In [82]:
#TODO
iris_1d = np.genfromtxt('Data/Iris.csv', delimiter=',', dtype=None, encoding=None)

# Get the petal lengths of setosa species
petal_lengths_setosa = iris_1d[1:, 2].astype(float)[iris_1d[1:, 4] == 'Iris-setosa']

# Sort the petal lengths in descending order
sorted_petal_lengths = np.sort(np.unique(petal_lengths_setosa))[::-1]

# The second longest petal length for setosa
second_longest_petal_length = sorted_petal_lengths[1]

# Display the result
print("Second longest petal length of species 'setosa':", second_longest_petal_length)

Second longest petal length of species 'setosa': 1.7
